# N/A II

# Q1
  


In [1]:
import numpy as np

# Create a vector of length 5 filled with random integers from 0 to 10
vector = np.random.randint(low=0, high=11, size=5)

# Print the vector
print(vector)

[9 0 6 0 7]


# Q2

In [3]:
# Create a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# Print all values except the first and last
print(vector[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# Q3

In [4]:
# Create a random array with 1000 elements
arr = np.random.rand(1000)

# Compute the average, variance, and standard deviation of the array
avg = np.mean(arr)
var = np.var(arr)
std = np.std(arr)

# Print results
print("Average:", avg)
print("Variance:", var)
print("Standard deviation:", std)



Average: 0.49512687948063194
Variance: 0.08110234781138274
Standard deviation: 0.2847847394285423


# Q4

In [5]:

# Create a 3x3 array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute the cumulative sum along the columns
cumsum_col = np.cumsum(arr, axis=0)

# Compute the cumulative sum along the rows
cumsum_row = np.cumsum(arr, axis=1)

# Sum over rows for each of the 3 columns
sum_rows_cols = np.sum(arr, axis=0)

# Sum over columns for each of the 2 rows
sum_cols_rows = np.sum(arr, axis=1)

# Print results
print("Original array:\n", arr)
print("\nCumulative sum along the columns:\n", cumsum_col)
print("\nCumulative sum along the rows:\n", cumsum_row)
print("\nSum over rows for each of the 3 columns:\n", sum_rows_cols)
print("\nSum over columns for each of the 2 rows:\n", sum_cols_rows)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Cumulative sum along the columns:
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]

Cumulative sum along the rows:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]

Sum over rows for each of the 3 columns:
 [12 15 18]

Sum over columns for each of the 2 rows:
 [ 6 15 24]


# Q5

In [6]:

# Define the two matrices
matrix1 = np.array([[1, 0], [0, 1]])
matrix2 = np.array([[1, 2], [3, 4]])

# Compute the multiplication of the two matrices
result = np.dot(matrix1, matrix2)

# Print result
print(result)


[[1 2]
 [3 4]]
